# This workflow creates a release using goreleaser
# via the 'make release' command.

name: Create release

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # ignore rc

permissions:
  contents: write

jobs:
  release:
    name: Create release
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      -
        name: Make release
        run: |
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
